/* ============================================================
   DATA LAYER — نظام العمل السعودي
   NOTE: Article texts here are REPRESENTATIVE SAMPLES for design
   purposes (flagged sample:true). They will be replaced with the
   verbatim official text. Simplified explanations & examples are
   unofficial. Chapter structure follows the law's 16-باب layout.
   ============================================================ */

const toAr = (n) => String(n).replace(/[0-9]/g, d => "٠١٢٣٤٥٦٧٨٩"[d]);
window.toAr = toAr;

window.LABOR = {
  meta: {
    title: "نظام العمل",
    titleEn: "Saudi Labor Law",
    decree: "المرسوم الملكي رقم م/٥١ وتاريخ ٢٣ / ٨ / ١٤٢٦هـ",
    decreeEn: "Royal Decree No. M/51, dated 23/8/1426 AH",
    chapters: 16,
    articles: 245,
    source: "https://laws.boe.gov.sa",
    latestAmendmentYear: "١٤٤٦",
  },

  chapters: [
    { n: 1,  from: 1,   to: 6,   count: 6,  title: "التعريفات والأحكام العامة", en: "Definitions & General Provisions" },
    { n: 2,  from: 7,   to: 31,  count: 25, title: "تنظيم عمليات التوظيف", en: "Regulation of Employment" },
    { n: 3,  from: 32,  to: 41,  count: 10, title: "توظيف غير السعوديين", en: "Employment of Non-Saudis" },
    { n: 4,  from: 42,  to: 49,  count: 8,  title: "التأهيل والتدريب", en: "Qualification & Training" },
    { n: 5,  from: 50,  to: 96,  count: 47, title: "علاقات العمل", en: "Work Relations" },
    { n: 6,  from: 97,  to: 136, count: 40, title: "شروط العمل وظروفه", en: "Work Conditions & Circumstances" },
    { n: 7,  from: 137, to: 140, count: 4,  title: "العمل لبعض الوقت", en: "Part-Time Work" },
    { n: 8,  from: 141, to: 170, count: 30, title: "الوقاية من مخاطر العمل وإصاباته والخدمات الصحية", en: "Protection, Injuries & Health Services" },
    { n: 9,  from: 171, to: 179, count: 9,  title: "تشغيل النساء", en: "Employment of Women" },
    { n: 10, from: 180, to: 186, count: 7,  title: "تشغيل الأحداث", en: "Employment of Minors" },
    { n: 11, from: 187, to: 199, count: 13, title: "عقد العمل البحري", en: "Maritime Work Contract" },
    { n: 12, from: 200, to: 208, count: 9,  title: "العمل في المناجم والمحاجر", en: "Work in Mines & Quarries" },
    { n: 13, from: 209, to: 216, count: 8,  title: "مفتّشو العمل", en: "Labor Inspectors" },
    { n: 14, from: 217, to: 229, count: 13, title: "هيئات تسوية الخلافات العمالية", en: "Labor Dispute Settlement" },
    { n: 15, from: 230, to: 241, count: 12, title: "العقوبات", en: "Penalties" },
    { n: 16, from: 242, to: 245, count: 4,  title: "أحكام ختامية", en: "Final Provisions" },
  ],

  articles: [
    {
      articleNumber: 2,
      chapter: { number: 1, title: "التعريفات والأحكام العامة" },
      section: { number: 1, title: "التعريفات" },
      isAmended: true,
      sample: true,
      officialText: "يُقصد بالألفاظ والعبارات الآتية — أينما وردت في هذا النظام — المعاني المبيّنة أمامها، ما لم يقتضِ السياق خلاف ذلك: العامل: كل شخص طبيعي يعمل لمصلحة صاحب عمل وتحت إدارته أو إشرافه مقابل أجر. صاحب العمل: كل شخص طبيعي أو اعتباري يشغّل عاملاً أو أكثر مقابل أجر. الأجر: كل ما يُعطى للعامل مقابل عمله بموجب عقد عمل مكتوب أو غير مكتوب، نقداً كان أو عيناً.",
      originalText: "يُقصد بالألفاظ والعبارات الآتية المعاني المبيّنة أمامها ما لم يقتضِ السياق خلاف ذلك … (الصياغة قبل التعديل).",
      amendmentInfo: "عُدّلت بالمرسوم الملكي رقم م/٤٤ وتاريخ ١٤٤٦هـ.",
      amendedYear: "١٤٤٦",
      amendedDecree: "م/٤٤",
      simplifiedAr: "هذه المادة تُعرّف المصطلحات الأساسية في النظام: مَن هو «العامل»، ومَن هو «صاحب العمل»، وما المقصود بـ«الأجر». فهمُها مفتاحٌ لفهم بقية المواد.",
      example: {
        scenario: "محاسب يعمل في شركة براتب شهري ويتلقّى تعليماته من المدير المالي.",
        outcome: "ينطبق عليه تعريف «العامل»، والشركة هي «صاحب العمل»، وراتبه الشهري هو «الأجر».",
      },
      keywords: ["العامل", "صاحب العمل", "الأجر", "تعريفات"],
      relatedArticles: [3, 50, 90],
      lastUpdated: "١٤٤٦",
    },
    {
      articleNumber: 74,
      chapter: { number: 5, title: "علاقات العمل" },
      section: { number: 4, title: "انتهاء عقد العمل" },
      isAmended: false,
      sample: true,
      officialText: "ينتهي عقد العمل في أيٍّ من الحالات الآتية: إذا اتفق الطرفان على إنهائه، بشرط أن تكون موافقة العامل كتابية. إذا انتهت المدة المحدّدة في العقد، ما لم يكن قد جُدّد صراحةً وفقاً لأحكام هذا النظام. إذا بلغ العامل سنّ التقاعد، ما لم يتفق الطرفان على الاستمرار. القوة القاهرة.",
      originalText: "",
      amendmentInfo: "",
      simplifiedAr: "تُحدّد هذه المادة الحالات التي ينتهي بها عقد العمل بشكل طبيعي ومشروع — مثل اتفاق الطرفين، أو انتهاء مدة العقد، أو بلوغ سن التقاعد، أو القوة القاهرة.",
      example: {
        scenario: "عقد محدد المدة لسنة واحدة انتهت مدّته ولم يُجدَّد من الطرفين.",
        outcome: "ينتهي عقد العمل تلقائياً بانتهاء مدّته دون الحاجة إلى إشعار.",
      },
      keywords: ["إنهاء العقد", "انتهاء العقد", "التقاعد", "القوة القاهرة"],
      relatedArticles: [75, 77, 80, 84],
      lastUpdated: "١٤٤٦",
    },
    {
      articleNumber: 75,
      chapter: { number: 5, title: "علاقات العمل" },
      section: { number: 4, title: "انتهاء عقد العمل" },
      isAmended: true,
      sample: true,
      officialText: "إذا كان العقد غير محدّد المدة، جاز لأيٍّ من الطرفين إنهاؤه بناءً على سبب مشروع، بموجب إشعارٍ كتابيٍّ يُوجَّه إلى الطرف الآخر قبل الإنهاء بمدة لا تقل عن ستين يوماً إذا كان أجر العامل يُدفع شهرياً، ولا تقل عن ثلاثين يوماً لغيره.",
      originalText: "… بمدة لا تقل عن ثلاثين يوماً (الصياغة قبل التعديل).",
      amendmentInfo: "عُدّلت مدة الإشعار بالمرسوم الملكي رقم م/٤٦ وتاريخ ١٤٣٦هـ.",
      amendedYear: "١٤٣٦",
      amendedDecree: "م/٤٦",
      simplifiedAr: "في العقود غير محددة المدة، يجب على من يريد الإنهاء أن يُخطر الطرف الآخر كتابياً قبل ٦٠ يوماً (للأجر الشهري) أو ٣٠ يوماً لغيره. هذه «مدة الإشعار».",
      example: {
        scenario: "موظف براتب شهري يرغب في الاستقالة، وعقده غير محدد المدة.",
        outcome: "عليه تقديم إشعار كتابي قبل ٦٠ يوماً على الأقل من تاريخ ترك العمل.",
      },
      keywords: ["إشعار", "مدة الإشعار", "استقالة", "إنهاء"],
      relatedArticles: [74, 76, 77],
      lastUpdated: "١٤٤٦",
    },
    {
      articleNumber: 77,
      chapter: { number: 5, title: "علاقات العمل" },
      section: { number: 4, title: "انتهاء عقد العمل" },
      isAmended: true,
      sample: true,
      officialText: "إذا أنهى أحد الطرفين العقد لسبب غير مشروع، يكون للطرف الآخر الحقّ في تعويضٍ: أجر خمسة عشر يوماً عن كل سنة من سنوات خدمة العامل في العقود غير محددة المدة، ومدة ما تبقّى من العقد في العقود محددة المدة، ما لم يتفق الطرفان على غير ذلك بما لا يقل عن أجر شهرين.",
      originalText: "",
      amendmentInfo: "عُدّلت بالمرسوم الملكي رقم م/٤٦ وتاريخ ١٤٣٦هـ.",
      amendedYear: "١٤٣٦",
      amendedDecree: "م/٤٦",
      simplifiedAr: "إذا فُصل العامل أو أُنهي عقده بدون سبب مشروع، فله تعويض: أجر ١٥ يوماً عن كل سنة خدمة في العقد غير محدد المدة، ولا يقل التعويض عن أجر شهرين.",
      example: {
        scenario: "موظف خدمته ٤ سنوات بعقد غير محدد المدة فُصل دون سبب نظامي، وأجره ٨٠٠٠ ريال.",
        outcome: "التعويض ≈ أجر ١٥ يوماً × ٤ سنوات = أجر ٦٠ يوماً (نحو ١٦٬٠٠٠ ريال)، بحد أدنى أجر شهرين.",
      },
      keywords: ["فصل تعسفي", "تعويض", "إنهاء غير مشروع"],
      relatedArticles: [74, 75, 80, 81],
      lastUpdated: "١٤٤٦",
    },
    {
      articleNumber: 84,
      chapter: { number: 5, title: "علاقات العمل" },
      section: { number: 4, title: "انتهاء عقد العمل" },
      isAmended: false,
      sample: true,
      officialText: "إذا انتهت علاقة العمل، وجب على صاحب العمل أن يدفع للعامل مكافأة عن مدة خدمته، تُحسب على أساس أجر نصف شهر عن كل سنة من السنوات الخمس الأولى، وأجر شهر عن كل سنة من السنوات التالية. ويُتّخذ الأجر الأخير أساساً لحساب المكافأة. ويستحق العامل مكافأة عن أجزاء السنة بنسبة ما قضاه منها في العمل.",
      originalText: "",
      amendmentInfo: "",
      simplifiedAr: "مكافأة نهاية الخدمة: نصف شهر عن كل سنة من أول ٥ سنوات، وشهر كامل عن كل سنة بعدها. يُحسب على أساس آخر أجر، وتُحتسب أجزاء السنة بالنسبة.",
      example: {
        scenario: "عامل خدمته ٨ سنوات وأجره الأخير ٦٠٠٠ ريال وانتهت خدمته.",
        outcome: "أول ٥ سنوات: ٥ × نصف شهر = ٢٫٥ شهر. الثلاث التالية: ٣ × شهر = ٣ أشهر. المجموع ٥٫٥ شهر × ٦٠٠٠ = ٣٣٬٠٠٠ ريال.",
      },
      keywords: ["مكافأة نهاية الخدمة", "نهاية الخدمة", "الأجر الأخير"],
      relatedArticles: [85, 86, 87, 88],
      lastUpdated: "١٤٤٦",
      calculator: "eos",
    },
    {
      articleNumber: 87,
      chapter: { number: 5, title: "علاقات العمل" },
      section: { number: 4, title: "انتهاء عقد العمل" },
      isAmended: false,
      sample: true,
      officialText: "استثناءً من المادة الرابعة والثمانين، إذا كان انتهاء العلاقة العمالية بسبب استقالة العامل، يستحق في هذه الحالة ثلث المكافأة بعد خدمة لا تقل مدّتها عن سنتين متتاليتين ولا تزيد على خمس سنوات، ويستحق ثلثيها إذا زادت مدّة خدمته على خمس سنوات متتالية ولم تبلغ عشر سنوات، ويستحق المكافأة كاملة إذا بلغت مدة خدمته عشر سنوات فأكثر.",
      originalText: "",
      amendmentInfo: "",
      simplifiedAr: "عند الاستقالة، تتأثر المكافأة بمدة الخدمة: ثلث المكافأة (٢–٥ سنوات)، ثلثاها (٥–١٠ سنوات)، وكاملة (١٠ سنوات فأكثر).",
      example: {
        scenario: "موظف استقال بعد ٦ سنوات خدمة.",
        outcome: "يستحق ثلثي مكافأة نهاية الخدمة المحسوبة وفق المادة ٨٤.",
      },
      keywords: ["استقالة", "مكافأة", "ثلث المكافأة"],
      relatedArticles: [84, 85],
      lastUpdated: "١٤٤٦",
      calculator: "eos",
    },
    {
      articleNumber: 107,
      chapter: { number: 6, title: "شروط العمل وظروفه" },
      section: { number: 2, title: "ساعات العمل" },
      isAmended: false,
      sample: true,
      officialText: "يجب على صاحب العمل أن يدفع للعامل — عن ساعات العمل الإضافية — أجراً إضافياً يوازي أجر الساعة مضافاً إليه ٥٠٪ من أجره الأساسي. وإذا كان العمل في المنشأة يُنظَّم على أساس معيار المدة الأسبوعية للساعات، فإنه يجوز تجاوز ثماني ساعات في اليوم بشرط ألا تزيد على ساعات العمل الأسبوعية المقررة.",
      originalText: "",
      amendmentInfo: "",
      simplifiedAr: "أي ساعة عمل إضافية تُحسب بأجر الساعة العادية + ٥٠٪. أي أن الساعة الإضافية = ١٫٥ ضعف أجر الساعة الاعتيادية.",
      example: {
        scenario: "عامل أجر ساعته العادية ٤٠ ريالاً عمل ١٠ ساعات إضافية في الشهر.",
        outcome: "أجر الساعة الإضافية = ٤٠ × ١٫٥ = ٦٠ ريالاً، والإجمالي = ١٠ × ٦٠ = ٦٠٠ ريال.",
      },
      keywords: ["أجر إضافي", "ساعات إضافية", "أوفر تايم", "overtime"],
      relatedArticles: [98, 106, 108],
      lastUpdated: "١٤٤٦",
      calculator: "ot",
    },
    {
      articleNumber: 109,
      chapter: { number: 6, title: "شروط العمل وظروفه" },
      section: { number: 4, title: "الإجازات" },
      isAmended: true,
      sample: true,
      officialText: "يستحق العامل عن كل عام إجازة سنوية لا تقل مدّتها عن واحدٍ وعشرين يوماً، تُزاد إلى مدةٍ لا تقل عن ثلاثين يوماً إذا أمضى العامل في خدمة صاحب العمل خمس سنوات متصلة. وتكون الإجازة بأجرٍ يُدفع مقدماً.",
      originalText: "",
      amendmentInfo: "عُدّلت بالمرسوم الملكي رقم م/٢٤ وتاريخ ١٤٣٤هـ.",
      amendedYear: "١٤٣٤",
      amendedDecree: "م/٢٤",
      simplifiedAr: "للعامل إجازة سنوية مدفوعة لا تقل عن ٢١ يوماً، تصبح ٣٠ يوماً بعد ٥ سنوات خدمة متصلة لدى صاحب العمل نفسه.",
      example: {
        scenario: "عامل أمضى ٦ سنوات متصلة لدى نفس صاحب العمل.",
        outcome: "يستحق إجازة سنوية لا تقل عن ٣٠ يوماً بأجر كامل.",
      },
      keywords: ["إجازة سنوية", "رصيد الإجازات", "إجازة مدفوعة"],
      relatedArticles: [110, 111, 112],
      lastUpdated: "١٤٤٦",
    },
    // ---- pending stubs (show the "not yet entered" state) ----
    { articleNumber: 1,  chapter: { number: 1, title: "التعريفات والأحكام العامة" }, status: "pending" },
    { articleNumber: 3,  chapter: { number: 1, title: "التعريفات والأحكام العامة" }, status: "pending" },
    { articleNumber: 50, chapter: { number: 5, title: "علاقات العمل" }, status: "pending" },
    { articleNumber: 85, chapter: { number: 5, title: "علاقات العمل" }, status: "pending" },
    { articleNumber: 90, chapter: { number: 6, title: "شروط العمل وظروفه" }, status: "pending" },
  ],

  glossary: [
    { term: "العامل", def: "كل شخص طبيعي يعمل لمصلحة صاحب عمل وتحت إدارته أو إشرافه مقابل أجر، ولو كان بعيداً عن نظارته." },
    { term: "صاحب العمل", def: "كل شخص طبيعي أو اعتباري يُشغّل عاملاً أو أكثر مقابل أجر." },
    { term: "الأجر", def: "كل ما يُعطى للعامل مقابل عمله بموجب عقد عمل، نقداً كان أو عيناً، ويشمل العمولات والبدلات بشروط معيّنة." },
    { term: "الأجر الأساسي", def: "كل ما يُعطى للعامل مقابل عمله بموجب عقد عمل مكتوب أو غير مكتوب، دون البدلات والعلاوات." },
    { term: "الخدمة المستمرة", def: "خدمة العامل غير المنقطعة لدى صاحب العمل نفسه أو خلفه النظامي، من تاريخ ابتداء الخدمة." },
    { term: "الإسناد", def: "تكليف صاحب العمل عاملاً بأداء عملٍ أصليٍّ لدى الغير لقاء أجر." },
    { term: "عقد العمل", def: "عقد مُبرم بين صاحب العمل والعامل، يتعهد بموجبه العامل بأن يعمل تحت إدارة صاحب العمل أو إشرافه مقابل أجر." },
  ],

  amendments: [
    { decree: "م/٥١", year: "١٤٢٦هـ", label: "النظام الأساسي", note: "صدور نظام العمل بالمرسوم الملكي م/٥١.", articles: "كامل النظام" },
    { decree: "م/٢٤", year: "١٤٣٤هـ", label: "تعديل", note: "تعديلات شملت أحكام الإجازات ومدد محددة.", articles: "منها م ١٠٩" },
    { decree: "م/٤٦", year: "١٤٣٦هـ", label: "تعديل موسّع", note: "تعديل واسع شمل مدد الإشعار والتعويضات والعقوبات.", articles: "منها م ٧٥، م ٧٧" },
    { decree: "م/١٣٤", year: "١٤٤٠هـ", label: "تعديل", note: "تحديثات على بعض أحكام علاقات العمل.", articles: "مواد متفرقة" },
    { decree: "م/٤٤", year: "١٤٤٦هـ", label: "أحدث تعديل", note: "أحدث حزمة تعديلات على التعريفات وأحكام عامة.", articles: "منها م ٢" },
  ],

  scenarios: [
    { id: "fired",     icon: "gavel",    title: "تم فصلي من العمل",         desc: "اعرف حقوقك عند الإنهاء والتعويض.",       articles: [74, 77, 80, 84] },
    { id: "resign",    icon: "exit",     title: "أريد تقديم استقالة",        desc: "مدة الإشعار وأثرها على المكافأة.",       articles: [75, 84, 87] },
    { id: "salary",    icon: "wallet",   title: "تأخّر صرف راتبي",          desc: "التزامات صاحب العمل تجاه الأجر.",        articles: [90, 92, 107] },
    { id: "injury",    icon: "shield",   title: "تعرّضت لإصابة عمل",        desc: "حقوقك في العلاج والتعويض.",             articles: [141, 142] },
    { id: "leave",     icon: "sun",      title: "حقوقي في الإجازات",        desc: "الإجازة السنوية والمرضية والطارئة.",     articles: [109, 110, 111] },
    { id: "overtime",  icon: "clock",    title: "ساعات العمل الإضافية",      desc: "كيف يُحسب الأجر الإضافي.",              articles: [98, 107] },
  ],
};

/* recently amended = amended in the newest amendment year on record */
window.isRecentlyAmended = (a) => !!(a && a.isAmended && a.amendedYear && a.amendedYear === LABOR.meta.latestAmendmentYear);
